# Generated by Django 4.2 on 2023-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgptapi', '0003_remove_fitnessgoal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='goal',
            field=models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('STRENGTH_GAIN', 'Strength Gain'), ('ENDURANCE_GAIN', 'Endurance Gain'), ('GENERAL_FITNESS', 'General Fitness'), ('METABOLIC_CONDITIONING_GAIN', 'Metabolic Conditioning Gain')], default='WEIGHT_LOSS', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='audience',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group')], default='INDIVIDUAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='fitness_experience',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PROFESSIONAL', 'Professional')], default='BEGINNER'),
        ),
    ]
