# Generated by Django 4.2 on 2023-04-28 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitgptapi', '0004_alter_fitnessgoal_goal_alter_fitnessprogram_audience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessprogram',
            name='fitness_goal',
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='experience',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PROFESSIONAL', 'Professional')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='fitnessprogram',
            name='goal',
            field=models.CharField(choices=[('ENDURANCE', 'Endurance'), ('METABOLIC_CONDITIONING', 'Metabolic Conditioning')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='audience',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('AFFILIATE', 'Affiliate'), ('GLOBAL', 'Global')], default='INDIVIDUAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FitnessGoal',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
