# Generated by Django 4.2 on 2023-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgptapi', '0005_remove_fitnessprogram_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprogram',
            name='audience',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('AFFILIATE', 'Affiliate'), ('GLOBAL', 'Global')], default='INDIVIDUAL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='experience',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('PROFESSIONAL', 'Professional')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessprogram',
            name='goal',
            field=models.CharField(choices=[('ENDURANCE', 'Endurance'), ('METABOLIC_CONDITIONING', 'Metabolic Conditioning')], default=None, max_length=255, null=True),
        ),
    ]
