# Generated by Django 4.2 on 2023-04-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitgptapi', '0007_alter_fitnessprogram_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('content', models.TextField(null=True)),
                ('scale', models.CharField(choices=[('RX', 'Rx'), ('SCALED', 'Scaled')], default='RX', max_length=255)),
                ('fitness_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitgptapi.fitnessprogram')),
            ],
        ),
    ]
