# Generated by Django 4.2 on 2023-04-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitgptapi', '0008_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ASSISTANT', 'Assistant')], max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('prompted_at', models.DateTimeField(null=True)),
                ('prompted_on', models.DateField(null=True)),
                ('fitness_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitgptapi.fitnessprogram')),
            ],
        ),
    ]
