# Generated by Django 4.2 on 2023-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitgptapi', '0011_alter_fitnessprogram_goal_alter_fitnessprogram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprogram',
            name='goal',
            field=models.CharField(blank=True, choices=[('ENDURANCE', 'Endurance'), ('METCON', 'Metcon'), ('BODYWEIGHT', 'Bodyweight')], default=None, max_length=255, null=True),
        ),
    ]
